EXECUTABLE	:= medianFilter
CUFILES		:= medianFilter_kernel.cu
CCFILES		:= medianFilter.cpp medianFilter_gold.cpp

include ../../common/common.mk
#NVCCFLAGS += --compiler-bindir /usr/bin/gcc-4.3
#CC=gcc-4.3
#CXX=g++-4.3
#LINK=gcc-4.3
